CREATE TABLE "CUSTOMER" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(255), "PASSWORD" VARCHAR(255), "EMAIL" VARCHAR(255)); 
CREATE TABLE "EVENTS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1), "EVENT_CODE" VARCHAR(255), "EVENT_TITLE" VARCHAR(255), "DESCRIPTION" VARCHAR(255));
CREATE TABLE "REGISTRATION" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1), "EVENT_ID" INTEGER NOT NULL, "CUSTOMER_ID" INTEGER NOT NULL, "REGISTRATION_DATE" TIMESTAMP, "NOTES" VARCHAR(255));


ALTER TABLE "CUSTOMER" ADD CONSTRAINT "SQL120325130144011" PRIMARY KEY ("ID");
ALTER TABLE "EVENTS" ADD CONSTRAINT "SQL120325130144012" PRIMARY KEY ("ID");
ALTER TABLE "REGISTRATION" ADD CONSTRAINT "SQL120325130144013" PRIMARY KEY ("ID");
